#!/bin/bash
echo "Starting test environment..."
docker-compose --env-file config.test.env  -f docker-compose.test.yml up -d

echo "Running tests..."
docker exec -ti trackmydeposits_api_test sh -c "yarn test"

echo "Shutting down test environment..."
docker-compose --env-file config.test.env -f docker-compose.test.yml down
